version: "3.1"

volumes:
  postgres_data: {}

services:
  db:
    image: postgres:10
    environment:
      POSTGRES_PASSWORD: ''
      POSTGRES_USER: ''
      POSTGRES_DB: ''
      PGDATA: '/var/lib/postgresql/data'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
    ports:
      - '5432:5432'
